language: python
os: linux
dist: bionic

services:
  - mysql

python:
  - "3.10"

env:
  - TESTENV=test

before_install:
  - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'

install:
  - pip install -e .[dev]

script:
  - if [[ "$TESTENV" == "test" ]]; then coverage run -m pytest --server=mysql://travis@127.0.0.1:3306/ src/python/tests; fi
  - if [[ "$TESTENV" == "test" ]]; then coverage report -m; fi
